// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ratelimit

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockLimiterStore creates a new instance of MockLimiterStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLimiterStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLimiterStore {
	mock := &MockLimiterStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLimiterStore is an autogenerated mock type for the LimiterStore type
type MockLimiterStore struct {
	mock.Mock
}

type MockLimiterStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLimiterStore) EXPECT() *MockLimiterStore_Expecter {
	return &MockLimiterStore_Expecter{mock: &_m.Mock}
}

// Allow provides a mock function for the type MockLimiterStore
func (_mock *MockLimiterStore) Allow(ctx context.Context, key string, limit int, window time.Duration) (bool, error) {
	ret := _mock.Called(ctx, key, limit, window)

	if len(ret) == 0 {
		panic("no return value specified for Allow")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, time.Duration) (bool, error)); ok {
		return returnFunc(ctx, key, limit, window)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, time.Duration) bool); ok {
		r0 = returnFunc(ctx, key, limit, window)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int, time.Duration) error); ok {
		r1 = returnFunc(ctx, key, limit, window)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLimiterStore_Allow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Allow'
type MockLimiterStore_Allow_Call struct {
	*mock.Call
}

// Allow is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - limit int
//   - window time.Duration
func (_e *MockLimiterStore_Expecter) Allow(ctx interface{}, key interface{}, limit interface{}, window interface{}) *MockLimiterStore_Allow_Call {
	return &MockLimiterStore_Allow_Call{Call: _e.mock.On("Allow", ctx, key, limit, window)}
}

func (_c *MockLimiterStore_Allow_Call) Run(run func(ctx context.Context, key string, limit int, window time.Duration)) *MockLimiterStore_Allow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockLimiterStore_Allow_Call) Return(b bool, err error) *MockLimiterStore_Allow_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockLimiterStore_Allow_Call) RunAndReturn(run func(ctx context.Context, key string, limit int, window time.Duration) (bool, error)) *MockLimiterStore_Allow_Call {
	_c.Call.Return(run)
	return _c
}
