// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handler

import (
	"context"

	"github.com/electr1fy0/okane/internal/payment"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPaymentService creates a new instance of MockPaymentService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPaymentService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPaymentService {
	mock := &MockPaymentService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPaymentService is an autogenerated mock type for the PaymentService type
type MockPaymentService struct {
	mock.Mock
}

type MockPaymentService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPaymentService) EXPECT() *MockPaymentService_Expecter {
	return &MockPaymentService_Expecter{mock: &_m.Mock}
}

// CreatePayment provides a mock function for the type MockPaymentService
func (_mock *MockPaymentService) CreatePayment(ctx context.Context, params payment.CreatePaymentParams) (*payment.Payment, bool, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for CreatePayment")
	}

	var r0 *payment.Payment
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, payment.CreatePaymentParams) (*payment.Payment, bool, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, payment.CreatePaymentParams) *payment.Payment); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*payment.Payment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, payment.CreatePaymentParams) bool); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, payment.CreatePaymentParams) error); ok {
		r2 = returnFunc(ctx, params)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockPaymentService_CreatePayment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePayment'
type MockPaymentService_CreatePayment_Call struct {
	*mock.Call
}

// CreatePayment is a helper method to define mock.On call
//   - ctx context.Context
//   - params payment.CreatePaymentParams
func (_e *MockPaymentService_Expecter) CreatePayment(ctx interface{}, params interface{}) *MockPaymentService_CreatePayment_Call {
	return &MockPaymentService_CreatePayment_Call{Call: _e.mock.On("CreatePayment", ctx, params)}
}

func (_c *MockPaymentService_CreatePayment_Call) Run(run func(ctx context.Context, params payment.CreatePaymentParams)) *MockPaymentService_CreatePayment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 payment.CreatePaymentParams
		if args[1] != nil {
			arg1 = args[1].(payment.CreatePaymentParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPaymentService_CreatePayment_Call) Return(payment1 *payment.Payment, b bool, err error) *MockPaymentService_CreatePayment_Call {
	_c.Call.Return(payment1, b, err)
	return _c
}

func (_c *MockPaymentService_CreatePayment_Call) RunAndReturn(run func(ctx context.Context, params payment.CreatePaymentParams) (*payment.Payment, bool, error)) *MockPaymentService_CreatePayment_Call {
	_c.Call.Return(run)
	return _c
}

// EnqueuePayment provides a mock function for the type MockPaymentService
func (_mock *MockPaymentService) EnqueuePayment(ctx context.Context, paymentID string) error {
	ret := _mock.Called(ctx, paymentID)

	if len(ret) == 0 {
		panic("no return value specified for EnqueuePayment")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, paymentID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPaymentService_EnqueuePayment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnqueuePayment'
type MockPaymentService_EnqueuePayment_Call struct {
	*mock.Call
}

// EnqueuePayment is a helper method to define mock.On call
//   - ctx context.Context
//   - paymentID string
func (_e *MockPaymentService_Expecter) EnqueuePayment(ctx interface{}, paymentID interface{}) *MockPaymentService_EnqueuePayment_Call {
	return &MockPaymentService_EnqueuePayment_Call{Call: _e.mock.On("EnqueuePayment", ctx, paymentID)}
}

func (_c *MockPaymentService_EnqueuePayment_Call) Run(run func(ctx context.Context, paymentID string)) *MockPaymentService_EnqueuePayment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPaymentService_EnqueuePayment_Call) Return(err error) *MockPaymentService_EnqueuePayment_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPaymentService_EnqueuePayment_Call) RunAndReturn(run func(ctx context.Context, paymentID string) error) *MockPaymentService_EnqueuePayment_Call {
	_c.Call.Return(run)
	return _c
}

// GetPaymentByID provides a mock function for the type MockPaymentService
func (_mock *MockPaymentService) GetPaymentByID(ctx context.Context, id string) (payment.Payment, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetPaymentByID")
	}

	var r0 payment.Payment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (payment.Payment, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) payment.Payment); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(payment.Payment)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPaymentService_GetPaymentByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPaymentByID'
type MockPaymentService_GetPaymentByID_Call struct {
	*mock.Call
}

// GetPaymentByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockPaymentService_Expecter) GetPaymentByID(ctx interface{}, id interface{}) *MockPaymentService_GetPaymentByID_Call {
	return &MockPaymentService_GetPaymentByID_Call{Call: _e.mock.On("GetPaymentByID", ctx, id)}
}

func (_c *MockPaymentService_GetPaymentByID_Call) Run(run func(ctx context.Context, id string)) *MockPaymentService_GetPaymentByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPaymentService_GetPaymentByID_Call) Return(payment1 payment.Payment, err error) *MockPaymentService_GetPaymentByID_Call {
	_c.Call.Return(payment1, err)
	return _c
}

func (_c *MockPaymentService_GetPaymentByID_Call) RunAndReturn(run func(ctx context.Context, id string) (payment.Payment, error)) *MockPaymentService_GetPaymentByID_Call {
	_c.Call.Return(run)
	return _c
}

// RetryFailedPayment provides a mock function for the type MockPaymentService
func (_mock *MockPaymentService) RetryFailedPayment(ctx context.Context, paymentID string) error {
	ret := _mock.Called(ctx, paymentID)

	if len(ret) == 0 {
		panic("no return value specified for RetryFailedPayment")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, paymentID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPaymentService_RetryFailedPayment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RetryFailedPayment'
type MockPaymentService_RetryFailedPayment_Call struct {
	*mock.Call
}

// RetryFailedPayment is a helper method to define mock.On call
//   - ctx context.Context
//   - paymentID string
func (_e *MockPaymentService_Expecter) RetryFailedPayment(ctx interface{}, paymentID interface{}) *MockPaymentService_RetryFailedPayment_Call {
	return &MockPaymentService_RetryFailedPayment_Call{Call: _e.mock.On("RetryFailedPayment", ctx, paymentID)}
}

func (_c *MockPaymentService_RetryFailedPayment_Call) Run(run func(ctx context.Context, paymentID string)) *MockPaymentService_RetryFailedPayment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPaymentService_RetryFailedPayment_Call) Return(err error) *MockPaymentService_RetryFailedPayment_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPaymentService_RetryFailedPayment_Call) RunAndReturn(run func(ctx context.Context, paymentID string) error) *MockPaymentService_RetryFailedPayment_Call {
	_c.Call.Return(run)
	return _c
}
