// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Payment struct {
	ID             pgtype.UUID
	Amount         int64
	Status         string
	IdempotencyKey string
	ProviderRef    pgtype.Text
	Attempts       pgtype.Int4
	LastError      pgtype.Text
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}
