// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
)

const createPayment = `-- name: CreatePayment :one
select id, amount, status, idempotency_key, provider_ref, attempts, last_error, created_at, updated_at from payments
`

func (q *Queries) CreatePayment(ctx context.Context) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.Status,
		&i.IdempotencyKey,
		&i.ProviderRef,
		&i.Attempts,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
