name: ci-tests

on: [push, pull_request]

jobs:
  test:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.26"
          cache: true

      - name: Run tests
        env:
          DB_URL: postgresql://okanedbuser:okanedbpass@localhost:5432/okanedb?sslmode=disable
        run: go test -v ./...

    services:
      postgres:
        image: postgres:18-alpine
        env:
          POSTGRES_USER: okanedbuser
          POSTGRES_PASSWORD: okanedbpass
          POSTGRES_DB: okanedb
        ports:
          - "5432:5432"
        options: >-
          --health-cmd "pg_isready -U okanedbuser -d okanedb"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5
